image: gradle:4.10.2

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
- build
- release
- publish
- downstream

build:
  stage: build
  script:
  - gradle clean check

snapshot:
  variables:
    OSSRH_REPO_URL: $SNAPSHOT_OSSRH_REPO_URL
  stage: release
  script:
  - gradle release
  only:
    refs:
      - master

release:
  variables:
    OSSRH_REPO_URL: $RELEASE_OSSRH_REPO_URL
  stage: release
  script:
  - gradle -Pversion=${CI_COMMIT_REF_NAME//release\/} release
  when: manual
  only:
    refs:
      - /^release\/(\d*).(\d*).(\d*)/

console:
  stage: publish
  script:
  - gradle -Pversion=${CI_COMMIT_REF_NAME//release\/} console:copyArtifiacts console:githubRelease
  only:
    refs:
      - /^release\/(\d*).(\d*).(\d*)/

homebrew:
  stage: downstream
  variables:
    GIT_STRATEGY: none
  script:
    - ./scripts/update-homebrew.sh
  only:
    refs:
      - /^release\/(\d*).(\d*).(\d*)/

dependants:
  stage: downstream
  variables:
    GIT_STRATEGY: none
  script:
    - ./scripts/build-dependant.sh quorum
  only:
    refs:
      - /^release\/(\d*).(\d*).(\d*)/
