image: gradle:alpine

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
  - .m2/repository/
  - target/

stages:
 - gitstuff
#- build
#- test

gitstuff:
  stage: build
  script:
    - git status

build:
  stage: build
  script:
  - gradle clean build

unit tests:
  stage: test
  script:
  - gradle test

# integration tests:

#  stage: test
#  script:
#    - $ ./gradlew  -Pintegration-tests=true :integration-tests:test
