image: gradle:alpine

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
  - .m2/repository/
  - target/

stages:
- build
- test
- deploy

build:
  stage: build
  script:
  - gradle clean build

unit tests:
  stage: test
  script:
  - gradle test

publish_snapshot:
  stage: deploy
  script:
  - echo "Publish to snapshot repository"
  environment:
    name: staging
    url: http://oss.sonatype.org/content/repositories/snapshots/
  when: manual
  only:
  - release/*

# integration tests:

#  stage: test
#  script:
#    - $ ./gradlew  -Pintegration-tests=true :integration-tests:test
