image: gradle:4.10.2

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper

stages:
- build
- release
- publish
- downstream

build-version:
  stage: build
  script:
    - ./gradlew check
  artifacts:
    paths:
      - scripts/
      - build/libs/
  only:
    refs:
      - /^release\/(\d*).(\d*).(\d*)/

release-version:
  variables:
    OSSRH_REPO_URL: $RELEASE_OSSRH_REPO_URL
  stage: release
  allow_failure: true
  script:
  - ./gradlew -Pversion=${CI_COMMIT_REF_NAME//release\/} release
  only:
    refs:
      - /^release\/(\d*).(\d*).(\d*)/

release-github:
  stage: publish
  script:
    - ./scripts/release-github.sh
  only:
    refs:
      - /^release\/(\d*).(\d*).(\d*)/

release-homebrew:
  stage: downstream
  variables:
    GIT_STRATEGY: none
  script:
    - ./scripts/update-homebrew.sh
  only:
    refs:
      - /^release\/(\d*).(\d*).(\d*)/
      
release-aur:
  stage: downstream
  variables:
    GIT_STRATEGY: none
  script:
    - ./scripts/update-aur.sh
  only:
    refs:
      - /^release\/(\d*).(\d*).(\d*)/

release-quorum:
  stage: downstream
  variables:
    GIT_STRATEGY: none
  script:
    - ./scripts/build-dependant.sh quorum
  only:
    refs:
      - /^release\/(\d*).(\d*).(\d*)/
