image: gradle:4.10.2

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
- build
- release
- publish
- downstream

build:
  stage: build
  script:
  - gradle clean check

snapshot:
  variables:
    OSSRH_REPO_URL: $SNAPSHOT_OSSRH_REPO_URL
  stage: release
  script:
  - gradle release
  only:
    refs:
      - master

maven:
  variables:
    OSSRH_REPO_URL: $RELEASE_OSSRH_REPO_URL
  stage: release
  script:
  - gradle -Pversion=${CI_COMMIT_REF_NAME//release\/} release
  when: manual
  only:
    refs:
      - /^release\/(\d*).(\d*).(\d*)/

console:
  stage: publish
  script:
  - gradle -Pversion=${CI_COMMIT_REF_NAME//release\/} console:publishArtifacts
  when: manual
  only:
    refs:
      - /^release\/(\d*).(\d*).(\d*)/

homebrew:
  stage: downstream
  variables:
    GIT_STRATEGY: none
    VERSION: ${CI_COMMIT_REF_NAME//release\/}
  script:
    - git config --global user.email "hi@web3labs.com"
    - git config --global user.name "Web3 Labs Team"
    - git clone https://iikirilov:${GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/web3j/homebrew-web3j.git
    - cd homebrew-web3j
    - sed -i "5s/.*/  url \"https:\/\/github.com\/web3j\/web3j\/releases\/download\/v${VERSION}\/web3j-${VERSION}.zip\"/" web3j.rb
    - SHA=$(curl -L https://github.com/web3j/web3j/releases/download/v${VERSION}/web3j-${VERSION}.zip | shasum -a 256 | tr -d ' ' | tr -d '-')
    - sed -i "7s/.*/  sha256 \"${SHA}\"/" web3j.rb
    - git commit -am "Change web3j version to ${VERSION}"
    - git push
  when: manual
  only:
    refs:
      - /^release\/(\d*).(\d*).(\d*)/
