image: gradle:4.10.2

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
  - .m2/repository/
  - target/

stages:
- build
- snapshot
- release

build:
  stage: build
  script:
  - gradle clean check

snapshot:
  variables:
    OSSRH_REPO_URL: $SNAPSHOT_OSSRH_REPO_URL
  stage: snapshot
  script:
  - gradle release
  only:
    refs:
      - master

release:
  variables:
    OSSRH_REPO_URL: $RELEASE_OSSRH_REPO_URL
  stage: release
  script:
  - gradle -Pversion=${CI_COMMIT_REF_NAME//release\/} release
  when: manual
  only:
    refs:
      - release\/(\d).(\d).(\d)
