name: Web3j

on:
  push:
    branches: [ master, 'release/*' ]
  pull_request:
    branches: [ master ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    env:
      registry.username: ${{ secrets.REGISTRY_USERNAME }}
      registry.password: ${{ secrets.REGISTRY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run integration tests
        run: ./gradlew integration-tests:test -Pintegration-tests=true
  build:
    runs-on: ubuntu-latest
    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
      GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew check jacocoTestReport
      - name: Decrypt secret key
        run: openssl aes-256-cbc -K ${{ secrets.GPG_KEY }} -iv ${{ secrets.GPG_IV }} -in web3j.asc.enc -out web3j.asc -d
        if: github.base_ref == ''
      - name: Publish master
        run: ./gradlew publish
        if: github.base_ref == ''
      - name: Release
        uses: web3j/release-action@v1.2
        with:
          version: ${GITHUB_REF#'release/'}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: contains(github.ref, '/release/')
      - name: After success
        run: bash <(curl -s https://codecov.io/bash)
        if: ${{ success() }}
